app/views.py
from flask import Blueprint, render_template, jsonify, request, redirect, url_for, session, send_file
import os
import json
from urllib.parse import unquote_plus, parse_qs
from werkzeug.utils import secure_filename
from utilities import register_user, process_request, get_mode, apply_watermark
from flask_login import logout_user, login_required, LoginManager
from models import Utilisateur, Contributeur, Image, Admin
from database_instance import db
from PIL import Image as Img


users = Blueprint("users_bp", __name__)
contrib = Blueprint("contrib_bp", __name__)
admin = Blueprint("admin_bp", __name__)
login_manager = LoginManager()


@users.route("/index")
def test():
    return render_template('main.html')

@users.route("/")
@login_required
def index():
    return redirect(url_for('users_bp.landing'))

@contrib.route("/contributor/images/<path:image_name>/<mimetype>")
def serve_image(image_name, mimetype):
    base_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), "watermarked_images\\" + image_name)
    return send_file(base_dir, mimetype='image/' + mimetype)

@contrib.route("/contributor/images", methods=['GET'])
@login_required
def get_images():
    page = request.args.get('page', default=1, type=int)
    per_page = request.args.get('per_page', default=2, type=int)
    images = Image.query.filter_by(contributeur_id=session.get('_user_id')).paginate(page=page, per_page=per_page)
    response = {
        'images': [image.render() for image in images.items],
        'total_pages': images.pages,
        'current_page': images.page,
        'has_prev': images.has_prev,
        'has_next': images.has_next
    }
    return jsonify(response)

@contrib.route("/contributor/images/<id>/delete", methods=['DELETE'])
@login_required
def delete(id):
    image = Image.query.filter_by(id=int(id)).first()
    if image:
        db.session.delete(image)
        db.session.commit()
        db.session.close()
        return jsonify({'message': 'Image deleted successfully', 'code_message': '200'})
    else:
        return jsonify({'message': 'Image doesn\'t exist', 'code_message': '400'})
    
@contrib.route("/contributor/images/<id>/edit", methods=['PUT'])
@login_required
def edit(id):
    data = request.get_data()
    decoded_data = unquote_plus(data.decode('utf-8'))
    parsed_data = parse_qs(decoded_data)
    # print(parsed_data.get('description'))
    image = Image.query.filter_by(id=int(id)).first()
    if image:
        image.description = parsed_data.get('description')[0]
        db.session.commit()
        db.session.close()
        return jsonify({'message': 'Image updated successfully', 'code_message': '200'})
    else:
        return jsonify({'message': 'Image doesn\'t exist', 'code_message': '400'})

@contrib.route("/upload", methods=["POST"])
def upload_image():
    if request.method == "POST":
        uploaded_file = request.files.get('image')
        if uploaded_file:
            filename = uploaded_file.filename
            filename = secure_filename(filename)
            filepath = os.path.join('uploads', filename)
            watermark_filepath = os.path.join('watermarked_images', filename)
            uploaded_file.save(filepath)
            apply_watermark(filepath, watermark_filepath, 65)
            description = request.form.get('description')
            title = request.form.get('title')
            auteur = request.form.get('auteur')
            payment_needed = True if request.form.get('paiement') == 'true' else False
            price = float(request.form.get('price')) if request.form.get('price') != '' else None
            contributor = Contributeur.query.get(session.get('_user_id'))
            with Img.open(filepath) as im:
                image = Image(image_url=filepath,
                              watermark_image_url=watermark_filepath,
                              description=description,
                              name=filename,
                              taille=(im.width * im.height),
                              format=im.format,
                              width=im.width,
                              height=im.height,
                              payment_required=payment_needed,
                              existing_licence=im.info.get('License') if im.info.get('License') is not None else im.info.get('license'),
                              price=price,
                              title=title,
                              auteur=auteur,
                              orientation=get_mode(im.width, im.height),
                              contributeur_id=contributor.id)
                db.session.add(image)
                db.session.commit()
                db.session.close()

            return jsonify({'message': 'Image saved successfully', 'code_message': '200'})
        else:
            return jsonify({'message': 'No image uploaded', 'code_message': '400'})


@users.route("/user/dashboard", endpoint="user-dashboard")
@login_required
def dashboard():
    return render_template("user/dashboard.html")

@users.route("/user/images/search", methods=['POST'])
@login_required
def images_search():
    page = request.args.get('page', default=1, type=int)
    per_page = request.args.get('per_page', default=2, type=int)
    image_format = request.form.get('format')
    resolution = json.loads(request.form.get('resolution'))
    mode = request.form.get('mode')
    payment = json.loads(request.form.get('payment'))
    query = Image.query.filter_by(status='VALIDATED')
    if image_format:
        query = query.filter(Image.format.ilike(image_format))
    if resolution:
        res_type, first_resolution, second_resolution = resolution.split(',')
        if res_type == 'faible':
            query = query.filter(Image.taille < int(first_resolution))
        if res_type == 'haute':
            query = query.filter(Image.taille > int(first_resolution))
        else:
            query = query.filter(Image.taille >= int(first_resolution), Image.taille <= int(second_resolution))
    
    if mode:
        query = query.filter(Image.orientation.ilike(mode))
    if payment:
        query = query.filter(Image.payment_required == payment)
            
    images = query.paginate(page=page, per_page=per_page)
    response = {
        'images': [image.render() for image in images.items],
        'total_pages': images.pages,
        'current_page': images.page,
        'has_prev': images.has_prev,
        'has_next': images.has_next
    }
    return jsonify(response)

@contrib.route("/contributor/dashboard", endpoint="contrib-dashboard")
@login_required
def dashboard():
    return render_template("contributor/dashboard.html")

@contrib.route("/contributor/upload", endpoint="contrib-upload")
@login_required
def dashboard():
    print(request.script_root)
    return render_template("contributor/upload.html")

@users.route("/home", endpoint="landing")
def landing():
    return render_template("login.html")


@users.route("/user/login", methods=['GET', 'POST'], endpoint="user-login")
def login():
    if request.method == "POST":
        username = request.form['username']
        password = request.form['password']
        return process_request(username, password, Utilisateur)
    return render_template('user/login.html')


@admin.route("/hidden/cave/admin/login", methods=['GET', 'POST'], endpoint="admin-login")
def login():
    if request.method == "POST":
        username = request.form['username']
        password = request.form['password']
        return process_request(username, password, Admin)
    return render_template('admin/login.html')


@contrib.route("/contributor/login", methods=['GET', 'POST'], endpoint="contrib-login")
def login():
    if request.method == "POST":
        username = request.form['username']
        password = request.form['password']
        return process_request(username, password, Contributeur)
    return render_template('contributor/login.html')


@users.route("/register", methods=['GET', 'POST'])
def register():
    return render_template('registration.html')


@users.route("/user/images", methods=['GET'])
def get_images():
    page = request.args.get('page', default=1, type=int)
    per_page = request.args.get('per_page', default=2, type=int)
    images = Image.query.filter_by(status='VALIDATED').paginate(page=page, per_page=per_page)
    response = {
        'images': [image.render() for image in images.items],
        'total_pages': images.pages,
        'current_page': images.page,
        'has_prev': images.has_prev,
        'has_next': images.has_next
    }
    return jsonify(response)


@users.route("/submit-registration", methods=['POST'])
def subscribe():
    username = request.form['username']
    email = request.form['email']
    password = request.form['password']
    is_registered = register_user(email, username, password, Utilisateur)
    if is_registered:
        return jsonify({'message': 'Registered successfully', 'code_message': '200'})
    else:
        return jsonify({'message': 'User already registered', 'code_message': '400'})


@contrib.route("/contributor/logout", endpoint="contrib-logout")
def logout():
    logout_user()
    if 'role' in session:
        session.pop('role')
    return redirect(url_for('users_bp.landing'))


@users.route("/user/logout", endpoint="user-logout")
def logout():
    logout_user()
    if 'role' in session:
        session.pop('role')
    return redirect(url_for('users_bp.landing'))

@users.route("/admin/logout", endpoint="admin-logout")
def logout():
    logout_user()
    if 'role' in session:
        session.pop('role')
    return redirect(url_for('admin_bp.admin-login'))

app/templates/user/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Contributor Dashboard - Image Bank App</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/noUiSlider/15.7.1/nouislider.min.css" integrity="sha512-qveKnGrvOChbSzAdtSs8p69eoLegyh+1hwOMbmpCViIwj7rn4oJjdmMvWOuyQlTOZgTlZA0N2PXA7iA8/2TUYA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="{{ url_for('static', filename='/css/user-dashboard.css') }}">
</head>
<body>
  <header>
    <nav>
      <ul>
        <li><a href="#" class="nav-link home" data-target="{{ url_for('static', filename='/components/user/accueil.html') }}">Accueil</a></li>
        <li><a href="#" class="nav-link" data-target="{{ url_for('static', filename='/components/user/images.html') }}">Mes Images</a></li>
        <li><a href="#" class="nav-link" data-target="settings">Règlages</a></li>
        <li><form action="{{ url_for('users_bp.user-logout') }}"><button type="submit" class="btn waves-effect" class="nav-link">Déconnexion</a></form></li>
      </ul>
    </nav>
  </header>

  <div id="content" class="container">
    <!-- Dynamic content here -->
  </div>

  <div id="modal1" class="modal modal-image">
    <div class="modal-content">
      <img style="display: none" id="previewImage" src="#" alt="Image Preview">
    </div>
    <div class="modal-footer">
      <a href="#!" class="modal-close waves-effect waves-green btn-flat close-confirm">Fermer</a>
    </div>
  </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/noUiSlider/15.7.1/nouislider.min.js" integrity="sha512-UOJe4paV6hYWBnS0c9GnIRH8PLm2nFK22uhfAvsTIqd3uwnWsVri1OPn5fJYdLtGY3wB11LGHJ4yPU1WFJeBYQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/wnumb/1.2.0/wNumb.min.js" integrity="sha512-igVQ7hyQVijOUlfg3OmcTZLwYJIBXU63xL9RC12xBHNpmGJAktDnzl9Iw0J4yrSaQtDxTTVlwhY730vphoVqJQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='/js/user-dashboard.js') }}">
    </script>
</body>
</html>

app/templates/user/login.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <title>Login</title>
    <!-- Include CSS stylesheets -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}">
</head>
<body>
    <div class="container">
        <h3>Login</h3>
        <form id="login-form" action="/login" method="post">
            <div class="input-field">
                <input type="text" id="username" name="username" required>
                <label for="username">Username</label>
            </div>
            <div class="input-field">
                <input type="password" id="password" name="password" required>
                <label for="password">Password</label>
            </div>
            <button type="submit" class="btn">Login</button>
        </form>
        <div>
            <a href="{{url_for('users_bp.register')}}">S'inscrire</a>
        </div>
    </div>

    <!-- Include JavaScript libraries -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <!-- Include your own JavaScript file -->
    <script src="{{ url_for('static', filename='js/user-login.js') }}"></script>
</body>
</html>